### ISSUE TITLE
Cannot install  node-libpng on ARM64 Ubuntu

### ISSUE THREAD

**Issue by rueceline** [Prior99/node-libpng#11]
Hi ,

I've been trying to install node-libpng on Ubuntu 16.04, But No supported arm64 linux.

I'm running node v10.14.0 and npm is v6.4.1.
Here is the output when I try to install node-libpng "npm i node-libpng"

Downloading node-libpng prebuilt binary from "https://github.com/Prior99/node-libpng/releases/download/0.2.7/node-libpng-linux-arm64-64.node".
/root/gpr/node_modules/node-libpng/scripts/install.js:30
            throw new Error(`No supported node-libpng ${packageVersion} build found for node ${process.version} on ${process.platform} (${process.arch}).`);
            ^

Error: No supported node-libpng 0.2.7 build found for node v10.14.0 on linux (arm64).
    at Request.request.get.on.on.response (/root/gpr/node_modules/node-libpng/scripts/install.js:30:19)
    at Request.emit (events.js:182:13)
    at Request.onRequestResponse (/root/gpr/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:441:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-libpng@0.2.7 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libpng@0.2.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-30T02_23_11_965Z-debug.log

**Comment by Prior99** [comment]
Hi.

Arm is currently not supported. Do you have experience wit ceosscompiling for ARM or a free ARM CI amd would like to add it?

**Comment by vielmetti** [comment]
@Prior99 There is a free ARM CI service using the new Drone Cloud  - see https://blog.drone.io/drone-cloud/ 

cc @bradrydzewski

**Comment by vielmetti** [comment]
More generally there is the @worksonarm project at http://www.worksonarm.com and we've been providing a variety of assistance to projects, happy to help.

**Comment by Prior99** [comment]
Thanks, I would happily accept and review a pullrequest adding Drone Cloud as a CI service, uploading releases to Github.
